#!/bin/sh
set -e
WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cat > "$WORKDIR/test.c" << 'CEOF'
#include <maxminddb.h>
#include <stdio.h>
int main(void) {
    printf("libmaxminddb version: %s\n", MMDB_lib_version());
    return 0;
}
CEOF
cd "$WORKDIR"
cc test.c -o test $(pkg-config --cflags --libs libmaxminddb)
./test
